In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import TruncatedSVD # TruncatedSVD
import pandas as pd

In [5]:
import sqlite3
cnx = sqlite3.connect('news-dbc.sqlite')

In [71]:
#  corpus = pd.read_csv("El Pais DataSet.csv")
#  del corpus['Title']
#  del corpus['Summary']
#  del corpus['Date']
#  del corpus['URL']
#  del corpus['ArticleID']


#  corpus.Content

0      last wednesday russian presid vladimir putin g...
1      china current experienc biggest spike coronavi...
2      cost gas continu rise unit state driver los an...
3      metropolitan museum new york collect 6000 obje...
4      intern space station bit like sixbedroom hous ...
                             ...
210    salomon die week jungl say jeff sagass utter p...
211    fall kabul lightn offens taliban afghanistan p...
212    second flight sent spain left kabul morn head ...
213    spanish tourism industri breath sigh relief le...
214    arriv spain state extrem exhaust carri belong ...
Name: Content, Length: 215, dtype: object

In [6]:
corpus = pd.read_sql_query("SELECT * FROM articles_processed ", cnx)
corpus.content

0       indian carrier air india report cancel delhimo...
1       usbas cyber secur group claim massiv cyberespi...
2       madra high court first bench chief justic muni...
3       yearold auto driver gautam kumar thakur caught...
4       ahead congress parti protest rise electr price...
                              ...
4943    rosario carrasco put home guarante son could g...
4944    last three year spain scientif communiti warn ...
4945    decad kind famili like stay headlin ran type c...
4946    week specul argentinean presid cristina fern√°n...
4947    question product never serious address spain e...
Name: content, Length: 4948, dtype: object

TFIDF vectorization

In [8]:
vectorizer=TfidfVectorizer(max_features=1000)
vectors = vectorizer.fit_transform(corpus.content)
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
df_vecs = pd.DataFrame(dense, columns=feature_names)
df_vecs

,abl,accept,access,accord,account,accus,achiev,across,act,action,...,world,worth,would,write,wrote,year,yearold,yet,you,young
0,0.000000,0.000000,0.000000,0.042010,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
1,0.000000,0.000000,0.030312,0.017819,0.000000,0.000000,0.000000,0.024805,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.014276,0.000000,0.000000,0.0,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.038487,0.0,0.0,0.031430,0.000000,0.000000,0.0,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.551459,0.000000,0.000000,0.114860,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.116972,0.000000,0.0,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077635,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4943,0.000000,0.000000,0.000000,0.000000,0.045862,0.061622,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.088933,0.0,0.0,0.048417,0.000000,0.000000,0.0,0.000000
4944,0.046686,0.000000,0.000000,0.015950,0.024209,0.000000,0.000000,0.000000,0.000000,0.0,...,0.051150,0.0,0.031297,0.0,0.0,0.153346,0.082796,0.000000,0.0,0.109075
4945,0.000000,0.039862,0.000000,0.000000,0.031158,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.082236,0.000000,0.000000,0.0,0.000000
4946,0.000000,0.000000,0.000000,0.000000,0.000000,0.060895,0.000000,0.000000,0.000000,0.0,...,0.031919,0.0,0.029295,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000
4947,0.011959,0.000000,0.013902,0.016344,0.012403,0.000000,0.014723,0.000000,0.000000,0.0,...,0.008735,0.0,0.040086,0.0,0.0,0.058924,0.000000,0.012445,0.0,0.000000

LDA

In [9]:
lda = LatentDirichletAllocation(n_components=15,learning_method='online', max_iter=20, random_state=100)
lda_matrix = lda.fit_transform(df_vecs)
lda_topics = lda.fit(df_vecs)

In [10]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print ("Topic" , topic_idx, " " .join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))
no_top_words = 10
display_topics(lda, feature_names, no_top_words)

Topic 0 appl russian iphon russia ukrain app googl user devic war
Topic 1 galaxi star planet observ earth discov solar nasa light object
Topic 2 kill ukrain russia russian india bodi child war independ peopl
Topic 3 spain said year also say one compani work new spanish
Topic 4 tax investig file court mumbai case incom wednesday hospit order
Topic 5 space earth nasa planet mission mar solar launch star surfac
Topic 6 vaccin infect covid case death patient virus cell health variant
Topic 7 polic bill fan soccer club said elect bodi delhi cup
Topic 8 polic minut share compani bank launch said food price report
Topic 9 strike employe polic child time man tri station hand son
Topic 10 polic earth station road congress man found got accus night
Topic 11 council ukrain human right russia said member general vote india
Topic 12 per cent point trade nifti price sensex stock index market
Topic 13 flight airlin airport passeng air nifti cancel strike oper ground
Topic 14 actress bar court father offici alleg said drug minist photo

LSA

In [11]:
sv_dec_lsa = TruncatedSVD(n_components = 15)
lsa_mat = sv_dec_lsa.fit_transform(vectors)
# Sigma = sv_dec_lsa.singular_values_ 
# V_transpose = sv_dec_lsa.components_.T
terms = vectorizer.get_feature_names()

In [12]:
display_topics(sv_dec_lsa, terms, no_top_words)

Topic 0 spain said year say also one compani work spanish peopl
Topic 1 per cent nifti point trade sensex index stock price market
Topic 2 spain tax govern spanish million economi billion countri tourism european
Topic 3 vaccin infect covid death case test studi virus health omicron
Topic 4 india game cricket indian match crore player olymp ipl tax
Topic 5 film movi actor vaccin death releas case covid crore infect
Topic 6 compani user space appl launch app film mission nasa earth
Topic 7 space film earth nasa planet mission star movi mar flight
Topic 8 per price cent tourist tourism space citi flight visitor island
Topic 9 court polic per tax alleg said minist cent russian investig
Topic 10 tax per price studi cent cell rate research crore incom
Topic 11 russia russian ukrain death countri khan war planet earth itali
Topic 12 tax million death case game appl player incom billion madrid
Topic 13 appl iphon price camera smartphon galaxi pro govern app phone
Topic 14 olymp russia india russian ukrain film medal energi world compani

In [55]:
# sv_dec = TruncatedSVD(n_components = 15)
# las = sv_dec.fit_transform(vectors)
# Sigma = sv_dec.singular_values_ 
# V_transpose = sv_dec.components_.T
# terms = vectorizer.get_feature_names()

# for index, component in enumerate(sv_dec.components_):
#     zipped = zip(terms, component)
#     top_terms_key=sorted(zipped, key = lambda t: t[1], reverse=True)[:10]
#     top_terms_list=list(dict(top_terms_key).keys())
#     print("Topic "+str(index)+": ",top_terms_list)

Topic 0:  ['per', 'cent', 'points', 'rs', 'said', 'nifty', 'sensex', 'india', 'also', 'prices']
Topic 1:  ['points', 'cent', 'per', 'nifty', 'sensex', 'stocks', 'previous', 'nse', 'traded', 'indices']
Topic 2:  ['rs', 'per', 'litre', 'petrol', 'prices', 'diesel', 'crore', 'price', 'paise', 'cases']
Topic 3:  ['cases', 'deaths', 'covid', 'csse', 'million', 'infections', 'toll', 'caseload', 'death', 'vaccine']
Topic 4:  ['film', 'movie', 'release', 'actor', 'films', 'director', 'box', 'actress', 'rrr', 'crore']
Topic 5:  ['cbi', 'study', 'case', 'court', 'said', 'deshmukh', 'police', 'cells', 'read', 'custody']
Topic 6:  ['cbi', 'court', 'case', 'deshmukh', 'police', 'minister', 'custody', 'khan', 'read', 'anil']
Topic 7:  ['cent', 'per', 'fell', 'khan', 'rate', 'us', 'shared', 'gained', 'media', 'cryptocurrency']
Topic 8:  ['cbi', 'deshmukh', 'case', 'covid', 'study', 'custody', 'variant', 'patients', 'film', 'cells']
Topic 9:  ['litre', 'petrol', 'prices', 'diesel', 'points', 'russia', 'khan', 'russian', 'ukraine', 'oil']
Topic 10:  ['cbi', 'space', 'earth', 'deshmukh', 'mars', 'planet', 'nasa', 'custody', 'mission', 'nasas']
Topic 11:  ['tokyo', 'olympics', 'gold', 'medal', 'games', 'olympic', 'silver', 'film', 'kg', 'athletes']
Topic 12:  ['khan', 'imran', 'film', 'pakistan', 'space', 'minister', 'earth', 'prime', 'assembly', 'mars']
Topic 13:  ['russian', 'film', 'ukraine', 'russia', 'ukrainian', 'india', 'war', 'bucha', 'oil', 'prices']
Topic 14:  ['russian', 'crore', 'ukraine', 'ukrainian', 'rs', 'russia', 'bucha', 'forces', 'war', 'bodies']

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [13]:
col = []
for i in range(lsa_mat.shape[1]):
    col.append("topic_{}".format(i)) 

topic_df = pd.DataFrame(lsa_mat, columns = col)

topic_df["Docs"] = corpus.content

l = ["Docs"]
for i in col:
    l.append(i)
topic_df

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_10,topic_11,topic_12,topic_13,topic_14,Docs
0,0.132660,0.021644,0.010555,0.084852,0.123247,-0.058470,0.091192,0.120727,0.110345,0.112532,-0.239385,-0.115151,-0.104795,-0.046934,0.051162,indian carrier air india report cancel delhimo...
1,0.298074,0.047898,-0.016836,0.105223,0.113802,-0.085979,0.151129,0.049819,-0.077172,-0.007726,-0.024524,-0.042810,-0.023275,0.033613,0.128834,usbas cyber secur group claim massiv cyberespi...
2,0.143541,0.011893,0.077373,0.001924,0.082619,0.016684,0.014559,0.022506,-0.098930,0.124930,0.019147,-0.005983,-0.091131,0.077652,0.016133,madra high court first bench chief justic muni...
3,0.146369,-0.017990,-0.006022,0.005885,0.034482,-0.013251,0.033614,-0.034407,-0.015714,0.174149,-0.032891,-0.046939,0.040239,0.048539,0.001363,yearold auto driver gautam kumar thakur caught...
4,0.190434,-0.013442,0.081635,-0.043835,0.094552,0.021767,0.023683,0.010841,-0.100631,0.252700,-0.018639,-0.013159,-0.144883,0.166337,0.038240,ahead congress parti protest rise electr price...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4943,0.438677,0.064353,-0.020112,-0.082504,-0.067915,-0.012577,0.000245,-0.126806,0.114653,0.017829,0.052475,0.010020,-0.080861,-0.041418,-0.016242,rosario carrasco put home guarante son could g...
4944,0.460999,-0.089605,0.094253,0.035620,-0.136993,-0.070136,-0.042644,0.050450,-0.056762,-0.074646,0.132953,0.024150,0.029744,-0.033020,0.076358,last three year spain scientif communiti warn ...
4945,0.423137,-0.119994,-0.069009,-0.095317,-0.042614,-0.037589,-0.014924,-0.145474,-0.012659,0.079149,-0.012216,-0.011066,-0.018492,-0.141394,-0.011392,decad kind famili like stay headlin ran type c...
4946,0.361888,0.007457,0.137247,-0.078524,0.098022,-0.010146,-0.007845,0.038280,-0.041502,0.125940,-0.056321,0.010420,-0.089901,0.073552,0.109718,week specul argentinean presid cristina fern√°n...
4947,0.453604,0.005094,0.214697,-0.109913,-0.060586,-0.024739,0.000533,-0.026287,0.030881,-0.192388,0.132076,0.050420,-0.031280,-0.047744,0.142066,question product never serious address spain e...

In [ ]:
print(topic_df.sum(axis=0))

topic_0                                            211.867124
topic_1                                            -50.295432
topic_2                                              4.782467
topic_3                                               -5.6033
topic_4                                              1.211433
topic_5                                             -2.662514
topic_6                                              4.745549
topic_7                                              0.901744
topic_8                                              3.045233
topic_9                                              2.236841
topic_10                                             2.809861
topic_11                                             1.081512
topic_12                                            -0.409772
topic_13                                             2.230564
topic_14                                             -3.40024
Docs        large number personal care cosmetic products p...
dtype: object